# Base tools - used in all environments including CI
[tools]
go = "1.25.4"
golangci-lint = "2.5.0"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "0.19.0"
"go:github.com/google/go-containerregistry/cmd/crane" = "0.20.6"
"aqua:pre-commit/pre-commit" = "4.6.0"
kind = "0.31.0"
kubectl = "1.32.1"
helm = "3.20.2"
helmfile = "1.2.3"
"github:kyverno/chainsaw" = "0.2.14"
tilt = "0.33.22"
"go:github.com/go-delve/delve/cmd/dlv" = "1.24.0"
"aqua:terrastruct/d2" = "0.7.1"
