// MIT License
//
// Copyright (c) 2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package controller

import (
	"context"
	"testing"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	aimv1alpha1 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha1"
	"github.com/amd-enterprise-ai/aim-engine/internal/constants"
)

func newTestReconciler(t *testing.T, objs ...*aimv1alpha1.AIMClusterModelSource) *AIMClusterModelSourceReconciler {
	t.Helper()
	scheme := runtime.NewScheme()
	if err := aimv1alpha1.AddToScheme(scheme); err != nil {
		t.Fatalf("AddToScheme() error = %v", err)
	}
	builder := fake.NewClientBuilder().WithScheme(scheme)
	for _, o := range objs {
		builder = builder.WithObjects(o)
	}
	return &AIMClusterModelSourceReconciler{Client: builder.Build(), Scheme: scheme}
}

func requestNames(reqs []reconcile.Request) []string {
	names := make([]string, 0, len(reqs))
	for _, r := range reqs {
		names = append(names, r.Name)
	}
	return names
}

func TestReserveSyncSlot_ThrottlesWithinFloor(t *testing.T) {
	r := &AIMClusterModelSourceReconciler{}

	// First attempt for a source is always allowed and records the attempt.
	if wait := r.reserveSyncSlot("source-a"); wait != 0 {
		t.Fatalf("first reserveSyncSlot() = %v, want 0 (allowed)", wait)
	}

	// An immediate second attempt is throttled within the floor.
	wait := r.reserveSyncSlot("source-a")
	if wait <= 0 || wait > minRegistrySyncInterval {
		t.Fatalf("second reserveSyncSlot() = %v, want within (0, %v]", wait, minRegistrySyncInterval)
	}

	// A different source is tracked independently and allowed immediately.
	if wait := r.reserveSyncSlot("source-b"); wait != 0 {
		t.Fatalf("reserveSyncSlot(source-b) = %v, want 0 (allowed)", wait)
	}

	// Once forgotten (source deleted), the next attempt is allowed again.
	r.forgetSyncAttempt("source-a")
	if wait := r.reserveSyncSlot("source-a"); wait != 0 {
		t.Fatalf("reserveSyncSlot after forget = %v, want 0 (allowed)", wait)
	}
}

func TestEnqueueAllSources(t *testing.T) {
	r := newTestReconciler(t,
		&aimv1alpha1.AIMClusterModelSource{ObjectMeta: metav1.ObjectMeta{Name: "source-a"}},
		&aimv1alpha1.AIMClusterModelSource{ObjectMeta: metav1.ObjectMeta{Name: "source-b"}},
	)

	got := requestNames(r.enqueueAllSources(context.Background(),
		&aimv1alpha1.AIMClusterModel{ObjectMeta: metav1.ObjectMeta{Name: "some-model"}}))

	if len(got) != 2 {
		t.Fatalf("enqueueAllSources() returned %d requests, want 2 (%v)", len(got), got)
	}
}

func TestEnqueueOtherSources_ExcludesTrigger(t *testing.T) {
	r := newTestReconciler(t,
		&aimv1alpha1.AIMClusterModelSource{ObjectMeta: metav1.ObjectMeta{Name: "source-a"}},
		&aimv1alpha1.AIMClusterModelSource{ObjectMeta: metav1.ObjectMeta{Name: "source-b"}},
	)

	got := requestNames(r.enqueueOtherSources(context.Background(),
		&aimv1alpha1.AIMClusterModelSource{ObjectMeta: metav1.ObjectMeta{Name: "source-a"}}))

	if len(got) != 1 || got[0] != "source-b" {
		t.Fatalf("enqueueOtherSources() = %v, want [source-b]", got)
	}
}

func TestAutoGeneratedClusterModelPredicate(t *testing.T) {
	auto := &aimv1alpha1.AIMClusterModel{ObjectMeta: metav1.ObjectMeta{
		Name:       "auto",
		Generation: 1,
		Labels:     map[string]string{constants.LabelKeyOrigin: constants.LabelValueOriginAutoGenerated},
	}}
	autoNextGen := auto.DeepCopy()
	autoNextGen.Generation = 2
	manual := &aimv1alpha1.AIMClusterModel{ObjectMeta: metav1.ObjectMeta{Name: "manual", Generation: 1}}

	p := autoGeneratedClusterModelPredicate()

	if p.Create(event.CreateEvent{Object: auto}) {
		t.Error("Create should never fire")
	}
	if !p.Delete(event.DeleteEvent{Object: auto}) {
		t.Error("Delete of auto-generated model should fire")
	}
	if p.Delete(event.DeleteEvent{Object: manual}) {
		t.Error("Delete of manual model should not fire")
	}
	if !p.Update(event.UpdateEvent{ObjectOld: auto, ObjectNew: autoNextGen}) {
		t.Error("Update of auto-generated model with spec change should fire")
	}
	if p.Update(event.UpdateEvent{ObjectOld: auto, ObjectNew: auto}) {
		t.Error("Update without generation change should not fire")
	}
}

func TestClusterModelSourceChangePredicate(t *testing.T) {
	src := &aimv1alpha1.AIMClusterModelSource{ObjectMeta: metav1.ObjectMeta{Name: "s", Generation: 1}}
	srcNextGen := src.DeepCopy()
	srcNextGen.Generation = 2

	p := clusterModelSourceChangePredicate()

	if p.Create(event.CreateEvent{Object: src}) {
		t.Error("Create should never fire")
	}
	if !p.Delete(event.DeleteEvent{Object: src}) {
		t.Error("Delete should fire")
	}
	if !p.Update(event.UpdateEvent{ObjectOld: src, ObjectNew: srcNextGen}) {
		t.Error("Update with spec change should fire")
	}
	if p.Update(event.UpdateEvent{ObjectOld: src, ObjectNew: src}) {
		t.Error("Update without generation change (status write) should not fire")
	}
}
