#!/usr/bin/env bash
#
# patch-helm-chart.sh - Post-process the kubebuilder-generated Helm chart
#
# This script applies customizations to the Helm chart generated by
# kubebuilder's helm/v2-alpha plugin. It handles:
# - Namespace templating (fix hardcoded aim-system)
# - imagePullSecrets support for the manager deployment
# - CRD removal (distributed separately)
# - Custom values.yaml and templates overlay
#
# Usage: ./hack/patch-helm-chart.sh
#
set -euo pipefail

CHART_DIR="dist/chart"
MANAGER_YAML="${CHART_DIR}/templates/manager/manager.yaml"

echo "Patching Helm chart at ${CHART_DIR}..."

# ------------------------------------------------------------------------------
# Fix hardcoded namespace in kubebuilder-generated templates
# Known limitation of helm/v2-alpha plugin
# ------------------------------------------------------------------------------
echo "  - Fixing hardcoded namespace references..."
find "${CHART_DIR}/templates" -name '*.yaml' -exec \
    sed -i 's/namespace: aim-system/namespace: {{ .Release.Namespace }}/g' {} \;

# ------------------------------------------------------------------------------
# Add imagePullSecrets support to manager deployment
# Injects templating after serviceAccountName to allow pulling from private registries
# ------------------------------------------------------------------------------
echo "  - Adding imagePullSecrets support to manager deployment..."
if [[ -f "${MANAGER_YAML}" ]]; then
    sed -i '/serviceAccountName: aim-engine-controller-manager/a\            {{- with .Values.manager.imagePullSecrets }}' "${MANAGER_YAML}"
    sed -i '/{{- with .Values.manager.imagePullSecrets }}/a\            imagePullSecrets:' "${MANAGER_YAML}"
    sed -i '/imagePullSecrets:$/a\              {{- toYaml . | nindent 14 }}' "${MANAGER_YAML}"
    sed -i '/{{- toYaml . | nindent 14 }}/a\            {{- end }}' "${MANAGER_YAML}"
else
    echo "    Warning: ${MANAGER_YAML} not found, skipping imagePullSecrets patch"
fi

# ------------------------------------------------------------------------------
# Wire the runtimeProjectionMode value to the operator's --runtime-projection-mode
# arg. The helm/v2-alpha plugin renders the manager args as a fixed
# --health-probe-bind-address line followed by a range over .Values.manager.args,
# so anchor on that fixed line and splice the flag right after it (preserving the
# line's indentation). Guarded so an empty value renders no arg (the operator then
# falls back to its compiled-in Exhaustive default); the shipped default value
# keeps projection in Exhaustive mode.
# ------------------------------------------------------------------------------
echo "  - Wiring runtimeProjectionMode to --runtime-projection-mode arg..."
if [[ -f "${MANAGER_YAML}" ]]; then
    sed -i 's|^\( *\)- --health-probe-bind-address=:8081$|&\n\1{{- if .Values.manager.runtimeProjectionMode }}\n\1- --runtime-projection-mode={{ .Values.manager.runtimeProjectionMode }}\n\1{{- end }}|' "${MANAGER_YAML}"
else
    echo "    Warning: ${MANAGER_YAML} not found, skipping runtime-projection-mode arg wiring"
fi

# ------------------------------------------------------------------------------
# Inject manager env block: scale-from-zero controller defaults, the dedicated
# manager.artifactDownloaderImage override (exposed as
# AIM_ARTIFACT_DOWNLOADER_IMAGE), plus any operator-supplied passthrough from
# .Values.manager.env. The kubebuilder helm/v2-alpha plugin emits no env:
# stanza, so we splice one in here. The artifactDownloaderImage override lets
# private installs point download Jobs at a non-public downloader mirror
# without rebuilding the operator binary.
# ------------------------------------------------------------------------------
echo "  - Adding manager env injection (scale-from-zero + artifactDownloaderImage)..."
if [[ -f "${MANAGER_YAML}" ]]; then
    python3 - "${MANAGER_YAML}" <<'PYEOF'
import re
import sys
path = sys.argv[1]
with open(path) as f:
    content = f.read()

match = re.search(
    r"^(?P<indent>[ \t]*)imagePullPolicy: "
    r"\{\{ \.Values\.manager\.image\.pullPolicy \}\}\n",
    content,
    flags=re.MULTILINE,
)
if not match:
    sys.stderr.write(f"WARN: imagePullPolicy marker not found in {path}; "
                     "skipping env injection\n")
    sys.exit(0)

indent = match.group("indent")
child_indent = indent + "  "
env_block = (
    f"{indent}env:\n"
    f"{child_indent}- name: AIM_KEDA_OTEL_SCALER_ADDRESS\n"
    f"{child_indent}  value: {{{{ .Values.scaleFromZero.scalerAddress | quote }}}}\n"
    f"{child_indent}- name: AIM_COOLDOWN_SECONDS_PER_GI_MEMORY\n"
    f"{child_indent}  value: {{{{ .Values.scaleFromZero.cooldownSecondsPerGiMemory | quote }}}}\n"
    f"{child_indent}{{{{- if .Values.manager.artifactDownloaderImage }}}}\n"
    f"{child_indent}- name: AIM_ARTIFACT_DOWNLOADER_IMAGE\n"
    f"{child_indent}  value: {{{{ .Values.manager.artifactDownloaderImage | quote }}}}\n"
    f"{child_indent}{{{{- end }}}}\n"
    f"{child_indent}{{{{- with .Values.manager.env }}}}\n"
    f"{child_indent}{{{{- toYaml . | nindent {len(child_indent)} }}}}\n"
    f"{child_indent}{{{{- end }}}}\n"
)

if "AIM_KEDA_OTEL_SCALER_ADDRESS" not in content:
    insert_at = match.end()
    content = content[:insert_at] + env_block + content[insert_at:]
    with open(path, "w") as f:
        f.write(content)
PYEOF
else
    echo "    Warning: ${MANAGER_YAML} not found, skipping env injection"
fi

# ------------------------------------------------------------------------------
# Add manager extraVolumes / extraVolumeMounts support. The generated manager
# deployment contains fixed empty arrays, so replace those exact anchors with
# values-driven blocks. This is used by the Kind stack to mount Zot's private
# CA, and is generally useful for other controller-side trust/config files.
# ------------------------------------------------------------------------------
echo "  - Adding manager extra volume support..."
if [[ -f "${MANAGER_YAML}" ]]; then
    python3 - "${MANAGER_YAML}" <<'PYEOF'
import re
import sys

path = sys.argv[1]
with open(path) as f:
    content = f.read()

def replace_empty_list(content, field, value_path):
    if value_path in content:
        return content

    marker = re.search(
        rf"^(?P<indent>[ \t]*){re.escape(field)}: \[\]\n",
        content,
        flags=re.MULTILINE,
    )
    if not marker:
        sys.stderr.write(f"ERROR: manager {field} marker not found in {path}\n")
        sys.exit(1)

    indent = marker.group("indent")
    child_indent = indent + "  "
    block = (
        f"{indent}{{{{- with {value_path} }}}}\n"
        f"{indent}{field}:\n"
        f"{child_indent}{{{{- toYaml . | nindent {len(child_indent)} }}}}\n"
        f"{indent}{{{{- else }}}}\n"
        f"{indent}{field}: []\n"
        f"{indent}{{{{- end }}}}\n"
    )
    return content[:marker.start()] + block + content[marker.end():]


content = replace_empty_list(
    content, "volumeMounts", ".Values.manager.extraVolumeMounts"
)
content = replace_empty_list(content, "volumes", ".Values.manager.extraVolumes")

with open(path, "w") as f:
    f.write(content)
PYEOF
else
    echo "    Warning: ${MANAGER_YAML} not found, skipping extra volume support"
fi

# ------------------------------------------------------------------------------
# Remove CRDs from chart - they are distributed separately
# This allows independent CRD lifecycle management
# ------------------------------------------------------------------------------
echo "  - Removing CRDs from chart (distributed separately)..."
rm -rf "${CHART_DIR}/templates/crd"

# ------------------------------------------------------------------------------
# Remove kustomize-generated add-on resources from other.yaml. These are
# replaced by custom Helm templates with values support:
#   - accelerator-detector  -> templates/accelerator-detector.yaml
#   - scale-from-zero collector (aim-scale-from-zero) -> templates/scale-from-zero-collector.yaml
# ------------------------------------------------------------------------------
OTHER_YAML="${CHART_DIR}/templates/other/other.yaml"
if [[ -f "${OTHER_YAML}" ]]; then
    echo "  - Removing kustomize-generated add-on resources from other.yaml..."
    python3 -c "
import re, sys
with open('${OTHER_YAML}') as f:
    content = f.read()
docs = re.split(r'^---$', content, flags=re.MULTILINE)
tokens = ('accelerator-detector', 'aim-scale-from-zero')
filtered = [d for d in docs if not any(t in d for t in tokens)]
with open('${OTHER_YAML}', 'w') as f:
    f.write('---'.join(filtered))
"
fi

# ------------------------------------------------------------------------------
# Remove the plugin-generated scale-from-zero collector RBAC fragment. The
# helm/v2-alpha plugin emits only the ClusterRoleBinding here (gated on
# metrics.enable, and missing its ServiceAccount + ClusterRole). The complete,
# values-driven set lives in templates/scale-from-zero-collector.yaml.
# ------------------------------------------------------------------------------
COLLECTOR_RBAC="${CHART_DIR}/templates/rbac/kgateway-metrics-collector.yaml"
if [[ -f "${COLLECTOR_RBAC}" ]]; then
    echo "  - Removing plugin-generated scale-from-zero collector RBAC fragment..."
    rm -f "${COLLECTOR_RBAC}"
fi

# ------------------------------------------------------------------------------
# Restore the manager ServiceAccount. Whenever extra RBAC (the scale-from-zero
# collector) is present in config/default, the helm/v2-alpha plugin drops
# ServiceAccount/aim-engine-controller-manager from its output -- even though
# the manager Deployment and its RoleBindings still reference it. Without this
# the operator pods fail to schedule ("serviceaccount not found"). We re-create
# the SA here to match what the plugin emits when no extra RBAC is present.
# ------------------------------------------------------------------------------
MANAGER_SA="${CHART_DIR}/templates/rbac/controller-manager.yaml"
if [[ ! -f "${MANAGER_SA}" ]]; then
    echo "  - Restoring manager ServiceAccount (dropped by helm/v2-alpha plugin)..."
    cat > "${MANAGER_SA}" <<'EOF'
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: aim-engine
  name: aim-engine-controller-manager
  namespace: {{ .Release.Namespace }}
EOF
fi

# ------------------------------------------------------------------------------
# Apply custom values.yaml if it exists
# Since dist/ is gitignored, we need persistent config in config/helm/
# ------------------------------------------------------------------------------
if [[ -f config/helm/values.yaml ]]; then
    echo "  - Applying custom values.yaml..."
    cp config/helm/values.yaml "${CHART_DIR}/values.yaml"
fi

# ------------------------------------------------------------------------------
# Copy custom templates if they exist
# Allows adding or overriding templates without modifying generated ones
# ------------------------------------------------------------------------------
if [[ -d config/helm/templates ]]; then
    echo "  - Copying custom templates..."
    cp -r config/helm/templates/* "${CHART_DIR}/templates/"
fi

# ------------------------------------------------------------------------------
# Copy shared files referenced by Helm templates via .Files.Get
# The detect-and-label.py script is shared between kustomize (configMapGenerator)
# and Helm (.Files.Get) to keep a single source of truth.
# ------------------------------------------------------------------------------
SCRIPT_SRC="config/accelerator-detector/scripts/detect-and-label.py"
if [[ -f "${SCRIPT_SRC}" ]]; then
    echo "  - Copying accelerator-detector script to chart files..."
    mkdir -p "${CHART_DIR}/files"
    cp "${SCRIPT_SRC}" "${CHART_DIR}/files/detect-and-label.py"
fi

echo "Helm chart patching complete."
