//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMAdapterDisk) DeepCopyInto(out *AIMAdapterDisk) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMAdapterDisk.
func (in *AIMAdapterDisk) DeepCopy() *AIMAdapterDisk {
	if in == nil {
		return nil
	}
	out := new(AIMAdapterDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMArtifact) DeepCopyInto(out *AIMArtifact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMArtifact.
func (in *AIMArtifact) DeepCopy() *AIMArtifact {
	if in == nil {
		return nil
	}
	out := new(AIMArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMArtifact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMArtifactConfig) DeepCopyInto(out *AIMArtifactConfig) {
	*out = *in
	if in.DefaultRetentionPriority != nil {
		in, out := &in.DefaultRetentionPriority, &out.DefaultRetentionPriority
		*out = new(int32)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3ConnectionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMArtifactConfig.
func (in *AIMArtifactConfig) DeepCopy() *AIMArtifactConfig {
	if in == nil {
		return nil
	}
	out := new(AIMArtifactConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMArtifactList) DeepCopyInto(out *AIMArtifactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMArtifactList.
func (in *AIMArtifactList) DeepCopy() *AIMArtifactList {
	if in == nil {
		return nil
	}
	out := new(AIMArtifactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMArtifactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMArtifactSpec) DeepCopyInto(out *AIMArtifactSpec) {
	*out = *in
	if in.CompatibleWith != nil {
		in, out := &in.CompatibleWith, &out.CompatibleWith
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rank != nil {
		in, out := &in.Rank, &out.Rank
		*out = new(int32)
		**out = **in
	}
	if in.AdapterDisk != nil {
		in, out := &in.AdapterDisk, &out.AdapterDisk
		*out = new(AIMAdapterDisk)
		(*in).DeepCopyInto(*out)
	}
	out.Size = in.Size.DeepCopy()
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DownloadFilter != nil {
		in, out := &in.DownloadFilter, &out.DownloadFilter
		*out = new(AIMDownloadFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.RetentionPriority != nil {
		in, out := &in.RetentionPriority, &out.RetentionPriority
		*out = new(int32)
		**out = **in
	}
	out.RuntimeConfigRef = in.RuntimeConfigRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMArtifactSpec.
func (in *AIMArtifactSpec) DeepCopy() *AIMArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(AIMArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMArtifactStatus) DeepCopyInto(out *AIMArtifactStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(DownloadProgress)
		**out = **in
	}
	if in.Download != nil {
		in, out := &in.Download, &out.Download
		*out = new(DownloadState)
		**out = **in
	}
	if in.LastUsed != nil {
		in, out := &in.LastUsed, &out.LastUsed
		*out = (*in).DeepCopy()
	}
	if in.DiscoveredSizeBytes != nil {
		in, out := &in.DiscoveredSizeBytes, &out.DiscoveredSizeBytes
		*out = new(int64)
		**out = **in
	}
	out.AllocatedSize = in.AllocatedSize.DeepCopy()
	if in.HeadroomPercent != nil {
		in, out := &in.HeadroomPercent, &out.HeadroomPercent
		*out = new(int32)
		**out = **in
	}
	if in.ResolvedParent != nil {
		in, out := &in.ResolvedParent, &out.ResolvedParent
		*out = new(AIMResolvedReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMArtifactStatus.
func (in *AIMArtifactStatus) DeepCopy() *AIMArtifactStatus {
	if in == nil {
		return nil
	}
	out := new(AIMArtifactStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMArtifactStorageQuota) DeepCopyInto(out *AIMArtifactStorageQuota) {
	*out = *in
	if in.ClusterLimit != nil {
		in, out := &in.ClusterLimit, &out.ClusterLimit
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DefaultNamespaceLimit != nil {
		in, out := &in.DefaultNamespaceLimit, &out.DefaultNamespaceLimit
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMArtifactStorageQuota.
func (in *AIMArtifactStorageQuota) DeepCopy() *AIMArtifactStorageQuota {
	if in == nil {
		return nil
	}
	out := new(AIMArtifactStorageQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterModel) DeepCopyInto(out *AIMClusterModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterModel.
func (in *AIMClusterModel) DeepCopy() *AIMClusterModel {
	if in == nil {
		return nil
	}
	out := new(AIMClusterModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterModelList) DeepCopyInto(out *AIMClusterModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMClusterModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterModelList.
func (in *AIMClusterModelList) DeepCopy() *AIMClusterModelList {
	if in == nil {
		return nil
	}
	out := new(AIMClusterModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterModelSource) DeepCopyInto(out *AIMClusterModelSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterModelSource.
func (in *AIMClusterModelSource) DeepCopy() *AIMClusterModelSource {
	if in == nil {
		return nil
	}
	out := new(AIMClusterModelSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterModelSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterModelSourceList) DeepCopyInto(out *AIMClusterModelSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMClusterModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterModelSourceList.
func (in *AIMClusterModelSourceList) DeepCopy() *AIMClusterModelSourceList {
	if in == nil {
		return nil
	}
	out := new(AIMClusterModelSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterModelSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterModelSourceSpec) DeepCopyInto(out *AIMClusterModelSourceSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]ModelSourceFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SyncInterval = in.SyncInterval
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxModels != nil {
		in, out := &in.MaxModels, &out.MaxModels
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterModelSourceSpec.
func (in *AIMClusterModelSourceSpec) DeepCopy() *AIMClusterModelSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AIMClusterModelSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterModelSourceStatus) DeepCopyInto(out *AIMClusterModelSourceStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterModelSourceStatus.
func (in *AIMClusterModelSourceStatus) DeepCopy() *AIMClusterModelSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AIMClusterModelSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterRuntimeConfig) DeepCopyInto(out *AIMClusterRuntimeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterRuntimeConfig.
func (in *AIMClusterRuntimeConfig) DeepCopy() *AIMClusterRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(AIMClusterRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterRuntimeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterRuntimeConfigList) DeepCopyInto(out *AIMClusterRuntimeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMClusterRuntimeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterRuntimeConfigList.
func (in *AIMClusterRuntimeConfigList) DeepCopy() *AIMClusterRuntimeConfigList {
	if in == nil {
		return nil
	}
	out := new(AIMClusterRuntimeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterRuntimeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterRuntimeConfigSpec) DeepCopyInto(out *AIMClusterRuntimeConfigSpec) {
	*out = *in
	in.AIMRuntimeConfigCommon.DeepCopyInto(&out.AIMRuntimeConfigCommon)
	if in.ArtifactStorageQuota != nil {
		in, out := &in.ArtifactStorageQuota, &out.ArtifactStorageQuota
		*out = new(AIMArtifactStorageQuota)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterRuntimeConfigSpec.
func (in *AIMClusterRuntimeConfigSpec) DeepCopy() *AIMClusterRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AIMClusterRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterServiceTemplate) DeepCopyInto(out *AIMClusterServiceTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterServiceTemplate.
func (in *AIMClusterServiceTemplate) DeepCopy() *AIMClusterServiceTemplate {
	if in == nil {
		return nil
	}
	out := new(AIMClusterServiceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterServiceTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterServiceTemplateList) DeepCopyInto(out *AIMClusterServiceTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMClusterServiceTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterServiceTemplateList.
func (in *AIMClusterServiceTemplateList) DeepCopy() *AIMClusterServiceTemplateList {
	if in == nil {
		return nil
	}
	out := new(AIMClusterServiceTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMClusterServiceTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMClusterServiceTemplateSpec) DeepCopyInto(out *AIMClusterServiceTemplateSpec) {
	*out = *in
	in.AIMServiceTemplateSpecCommon.DeepCopyInto(&out.AIMServiceTemplateSpecCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMClusterServiceTemplateSpec.
func (in *AIMClusterServiceTemplateSpec) DeepCopy() *AIMClusterServiceTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AIMClusterServiceTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMCpuRequirements) DeepCopyInto(out *AIMCpuRequirements) {
	*out = *in
	out.Requests = in.Requests.DeepCopy()
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMCpuRequirements.
func (in *AIMCpuRequirements) DeepCopy() *AIMCpuRequirements {
	if in == nil {
		return nil
	}
	out := new(AIMCpuRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMCustomModelSpec) DeepCopyInto(out *AIMCustomModelSpec) {
	*out = *in
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(AIMHardwareRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(AIMProfileType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMCustomModelSpec.
func (in *AIMCustomModelSpec) DeepCopy() *AIMCustomModelSpec {
	if in == nil {
		return nil
	}
	out := new(AIMCustomModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMCustomProfile) DeepCopyInto(out *AIMCustomProfile) {
	*out = *in
	if in.EngineArgs != nil {
		in, out := &in.EngineArgs, &out.EngineArgs
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMCustomProfile.
func (in *AIMCustomProfile) DeepCopy() *AIMCustomProfile {
	if in == nil {
		return nil
	}
	out := new(AIMCustomProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMCustomTemplate) DeepCopyInto(out *AIMCustomTemplate) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(AIMHardwareRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(AIMTemplateProfile)
		**out = **in
	}
	if in.CustomProfile != nil {
		in, out := &in.CustomProfile, &out.CustomProfile
		*out = new(AIMCustomProfile)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMCustomTemplate.
func (in *AIMCustomTemplate) DeepCopy() *AIMCustomTemplate {
	if in == nil {
		return nil
	}
	out := new(AIMCustomTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMDiscoveredProfile) DeepCopyInto(out *AIMDiscoveredProfile) {
	*out = *in
	if in.EngineArgs != nil {
		in, out := &in.EngineArgs, &out.EngineArgs
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Metadata = in.Metadata
	if in.OriginalDiscoveryOutput != nil {
		in, out := &in.OriginalDiscoveryOutput, &out.OriginalDiscoveryOutput
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMDiscoveredProfile.
func (in *AIMDiscoveredProfile) DeepCopy() *AIMDiscoveredProfile {
	if in == nil {
		return nil
	}
	out := new(AIMDiscoveredProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMDiscoveryProfile) DeepCopyInto(out *AIMDiscoveryProfile) {
	*out = *in
	if in.EngineArgs != nil {
		in, out := &in.EngineArgs, &out.EngineArgs
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Metadata = in.Metadata
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMDiscoveryProfile.
func (in *AIMDiscoveryProfile) DeepCopy() *AIMDiscoveryProfile {
	if in == nil {
		return nil
	}
	out := new(AIMDiscoveryProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMDiscoveryProfileMetadata) DeepCopyInto(out *AIMDiscoveryProfileMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMDiscoveryProfileMetadata.
func (in *AIMDiscoveryProfileMetadata) DeepCopy() *AIMDiscoveryProfileMetadata {
	if in == nil {
		return nil
	}
	out := new(AIMDiscoveryProfileMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMDownloadFilter) DeepCopyInto(out *AIMDownloadFilter) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMDownloadFilter.
func (in *AIMDownloadFilter) DeepCopy() *AIMDownloadFilter {
	if in == nil {
		return nil
	}
	out := new(AIMDownloadFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMGpuRequirements) DeepCopyInto(out *AIMGpuRequirements) {
	*out = *in
	if in.MinVRAM != nil {
		in, out := &in.MinVRAM, &out.MinVRAM
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMGpuRequirements.
func (in *AIMGpuRequirements) DeepCopy() *AIMGpuRequirements {
	if in == nil {
		return nil
	}
	out := new(AIMGpuRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMHardwareRequirements) DeepCopyInto(out *AIMHardwareRequirements) {
	*out = *in
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(AIMGpuRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(AIMCpuRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMHardwareRequirements.
func (in *AIMHardwareRequirements) DeepCopy() *AIMHardwareRequirements {
	if in == nil {
		return nil
	}
	out := new(AIMHardwareRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModel) DeepCopyInto(out *AIMModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModel.
func (in *AIMModel) DeepCopy() *AIMModel {
	if in == nil {
		return nil
	}
	out := new(AIMModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelConfig) DeepCopyInto(out *AIMModelConfig) {
	*out = *in
	if in.AutoDiscovery != nil {
		in, out := &in.AutoDiscovery, &out.AutoDiscovery
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelConfig.
func (in *AIMModelConfig) DeepCopy() *AIMModelConfig {
	if in == nil {
		return nil
	}
	out := new(AIMModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelDiscoveryConfig) DeepCopyInto(out *AIMModelDiscoveryConfig) {
	*out = *in
	if in.ExtractMetadata != nil {
		in, out := &in.ExtractMetadata, &out.ExtractMetadata
		*out = new(bool)
		**out = **in
	}
	if in.CreateServiceTemplates != nil {
		in, out := &in.CreateServiceTemplates, &out.CreateServiceTemplates
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelDiscoveryConfig.
func (in *AIMModelDiscoveryConfig) DeepCopy() *AIMModelDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(AIMModelDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelList) DeepCopyInto(out *AIMModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelList.
func (in *AIMModelList) DeepCopy() *AIMModelList {
	if in == nil {
		return nil
	}
	out := new(AIMModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelProfilesDerivedFrom) DeepCopyInto(out *AIMModelProfilesDerivedFrom) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(ProfileSourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelProfilesDerivedFrom.
func (in *AIMModelProfilesDerivedFrom) DeepCopy() *AIMModelProfilesDerivedFrom {
	if in == nil {
		return nil
	}
	out := new(AIMModelProfilesDerivedFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelProfilesSpec) DeepCopyInto(out *AIMModelProfilesSpec) {
	*out = *in
	if in.DerivedFrom != nil {
		in, out := &in.DerivedFrom, &out.DerivedFrom
		*out = new(AIMModelProfilesDerivedFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(ProfileOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelProfilesSpec.
func (in *AIMModelProfilesSpec) DeepCopy() *AIMModelProfilesSpec {
	if in == nil {
		return nil
	}
	out := new(AIMModelProfilesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelSource) DeepCopyInto(out *AIMModelSource) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelSource.
func (in *AIMModelSource) DeepCopy() *AIMModelSource {
	if in == nil {
		return nil
	}
	out := new(AIMModelSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelSpec) DeepCopyInto(out *AIMModelSpec) {
	*out = *in
	if in.ProfileCopy != nil {
		in, out := &in.ProfileCopy, &out.ProfileCopy
		*out = new(AIMProfileSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DerivedFrom != nil {
		in, out := &in.DerivedFrom, &out.DerivedFrom
		*out = new(AIMProfileSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = new(AIMModelProfilesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(AIMModelDiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(AIMCustomModelSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomTemplates != nil {
		in, out := &in.CustomTemplates, &out.CustomTemplates
		*out = make([]AIMCustomTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RuntimeConfigRef = in.RuntimeConfigRef
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ImageMetadata != nil {
		in, out := &in.ImageMetadata, &out.ImageMetadata
		*out = new(ImageMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelSpec.
func (in *AIMModelSpec) DeepCopy() *AIMModelSpec {
	if in == nil {
		return nil
	}
	out := new(AIMModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMModelStatus) DeepCopyInto(out *AIMModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedRuntimeConfig != nil {
		in, out := &in.ResolvedRuntimeConfig, &out.ResolvedRuntimeConfig
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ImageMetadata != nil {
		in, out := &in.ImageMetadata, &out.ImageMetadata
		*out = new(ImageMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscoveryCacheRef != nil {
		in, out := &in.DiscoveryCacheRef, &out.DiscoveryCacheRef
		*out = new(DiscoveryCacheReference)
		**out = **in
	}
	in.DiscoveredProfiles.DeepCopyInto(&out.DiscoveredProfiles)
	if in.ProfileSetRef != nil {
		in, out := &in.ProfileSetRef, &out.ProfileSetRef
		*out = new(ProfileSetReference)
		**out = **in
	}
	out.ManagedProfiles = in.ManagedProfiles
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(ModelDiscoveryState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMModelStatus.
func (in *AIMModelStatus) DeepCopy() *AIMModelStatus {
	if in == nil {
		return nil
	}
	out := new(AIMModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMProfileMetadata) DeepCopyInto(out *AIMProfileMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMProfileMetadata.
func (in *AIMProfileMetadata) DeepCopy() *AIMProfileMetadata {
	if in == nil {
		return nil
	}
	out := new(AIMProfileMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMProfileSetSpec) DeepCopyInto(out *AIMProfileSetSpec) {
	*out = *in
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(ProfileSourceRef)
		**out = **in
	}
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(ProfileOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMProfileSetSpec.
func (in *AIMProfileSetSpec) DeepCopy() *AIMProfileSetSpec {
	if in == nil {
		return nil
	}
	out := new(AIMProfileSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMProfileSetStatus) DeepCopyInto(out *AIMProfileSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ManagedProfiles = in.ManagedProfiles
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMProfileSetStatus.
func (in *AIMProfileSetStatus) DeepCopy() *AIMProfileSetStatus {
	if in == nil {
		return nil
	}
	out := new(AIMProfileSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMResolvedArtifact) DeepCopyInto(out *AIMResolvedArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMResolvedArtifact.
func (in *AIMResolvedArtifact) DeepCopy() *AIMResolvedArtifact {
	if in == nil {
		return nil
	}
	out := new(AIMResolvedArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMResolvedReference) DeepCopyInto(out *AIMResolvedReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMResolvedReference.
func (in *AIMResolvedReference) DeepCopy() *AIMResolvedReference {
	if in == nil {
		return nil
	}
	out := new(AIMResolvedReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeConfig) DeepCopyInto(out *AIMRuntimeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeConfig.
func (in *AIMRuntimeConfig) DeepCopy() *AIMRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMRuntimeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeConfigCommon) DeepCopyInto(out *AIMRuntimeConfigCommon) {
	*out = *in
	in.AIMServiceRuntimeConfig.DeepCopyInto(&out.AIMServiceRuntimeConfig)
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(AIMModelConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(AIMArtifactConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ArtifactCache != nil {
		in, out := &in.ArtifactCache, &out.ArtifactCache
		*out = new(ArtifactCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelPropagation != nil {
		in, out := &in.LabelPropagation, &out.LabelPropagation
		*out = new(AIMRuntimeConfigLabelPropagationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCHeadroomPercent != nil {
		in, out := &in.PVCHeadroomPercent, &out.PVCHeadroomPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeConfigCommon.
func (in *AIMRuntimeConfigCommon) DeepCopy() *AIMRuntimeConfigCommon {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeConfigCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeConfigLabelPropagationSpec) DeepCopyInto(out *AIMRuntimeConfigLabelPropagationSpec) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeConfigLabelPropagationSpec.
func (in *AIMRuntimeConfigLabelPropagationSpec) DeepCopy() *AIMRuntimeConfigLabelPropagationSpec {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeConfigLabelPropagationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeConfigList) DeepCopyInto(out *AIMRuntimeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMRuntimeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeConfigList.
func (in *AIMRuntimeConfigList) DeepCopy() *AIMRuntimeConfigList {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMRuntimeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeConfigSpec) DeepCopyInto(out *AIMRuntimeConfigSpec) {
	*out = *in
	in.AIMRuntimeConfigCommon.DeepCopyInto(&out.AIMRuntimeConfigCommon)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeConfigSpec.
func (in *AIMRuntimeConfigSpec) DeepCopy() *AIMRuntimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeConfigStatus) DeepCopyInto(out *AIMRuntimeConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeConfigStatus.
func (in *AIMRuntimeConfigStatus) DeepCopy() *AIMRuntimeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeParameters) DeepCopyInto(out *AIMRuntimeParameters) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(AIMMetric)
		**out = **in
	}
	if in.Precision != nil {
		in, out := &in.Precision, &out.Precision
		*out = new(AIMPrecision)
		**out = **in
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(AIMHardwareRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeParameters.
func (in *AIMRuntimeParameters) DeepCopy() *AIMRuntimeParameters {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMRuntimeRoutingConfig) DeepCopyInto(out *AIMRuntimeRoutingConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GatewayRef != nil {
		in, out := &in.GatewayRef, &out.GatewayRef
		*out = new(apisv1.ParentReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]apisv1.Hostname, len(*in))
		copy(*out, *in)
	}
	if in.PathTemplate != nil {
		in, out := &in.PathTemplate, &out.PathTemplate
		*out = new(string)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMRuntimeRoutingConfig.
func (in *AIMRuntimeRoutingConfig) DeepCopy() *AIMRuntimeRoutingConfig {
	if in == nil {
		return nil
	}
	out := new(AIMRuntimeRoutingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMScaleFromZeroConfig) DeepCopyInto(out *AIMScaleFromZeroConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMScaleFromZeroConfig.
func (in *AIMScaleFromZeroConfig) DeepCopy() *AIMScaleFromZeroConfig {
	if in == nil {
		return nil
	}
	out := new(AIMScaleFromZeroConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMService) DeepCopyInto(out *AIMService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMService.
func (in *AIMService) DeepCopy() *AIMService {
	if in == nil {
		return nil
	}
	out := new(AIMService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceAdapterReference) DeepCopyInto(out *AIMServiceAdapterReference) {
	*out = *in
	if in.Rank != nil {
		in, out := &in.Rank, &out.Rank
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceAdapterReference.
func (in *AIMServiceAdapterReference) DeepCopy() *AIMServiceAdapterReference {
	if in == nil {
		return nil
	}
	out := new(AIMServiceAdapterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceAdapterStatus) DeepCopyInto(out *AIMServiceAdapterStatus) {
	*out = *in
	if in.LastObserved != nil {
		in, out := &in.LastObserved, &out.LastObserved
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceAdapterStatus.
func (in *AIMServiceAdapterStatus) DeepCopy() *AIMServiceAdapterStatus {
	if in == nil {
		return nil
	}
	out := new(AIMServiceAdapterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceAutoScaling) DeepCopyInto(out *AIMServiceAutoScaling) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]AIMServiceMetricsSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PollingInterval != nil {
		in, out := &in.PollingInterval, &out.PollingInterval
		*out = new(int32)
		**out = **in
	}
	if in.CooldownPeriod != nil {
		in, out := &in.CooldownPeriod, &out.CooldownPeriod
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceAutoScaling.
func (in *AIMServiceAutoScaling) DeepCopy() *AIMServiceAutoScaling {
	if in == nil {
		return nil
	}
	out := new(AIMServiceAutoScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceCacheStatus) DeepCopyInto(out *AIMServiceCacheStatus) {
	*out = *in
	if in.TemplateCacheRef != nil {
		in, out := &in.TemplateCacheRef, &out.TemplateCacheRef
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ProfileCacheRef != nil {
		in, out := &in.ProfileCacheRef, &out.ProfileCacheRef
		*out = new(AIMResolvedReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceCacheStatus.
func (in *AIMServiceCacheStatus) DeepCopy() *AIMServiceCacheStatus {
	if in == nil {
		return nil
	}
	out := new(AIMServiceCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceCachingConfig) DeepCopyInto(out *AIMServiceCachingConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceCachingConfig.
func (in *AIMServiceCachingConfig) DeepCopy() *AIMServiceCachingConfig {
	if in == nil {
		return nil
	}
	out := new(AIMServiceCachingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceList) DeepCopyInto(out *AIMServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceList.
func (in *AIMServiceList) DeepCopy() *AIMServiceList {
	if in == nil {
		return nil
	}
	out := new(AIMServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceMetricTarget) DeepCopyInto(out *AIMServiceMetricTarget) {
	*out = *in
	if in.AverageUtilization != nil {
		in, out := &in.AverageUtilization, &out.AverageUtilization
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceMetricTarget.
func (in *AIMServiceMetricTarget) DeepCopy() *AIMServiceMetricTarget {
	if in == nil {
		return nil
	}
	out := new(AIMServiceMetricTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceMetricsSpec) DeepCopyInto(out *AIMServiceMetricsSpec) {
	*out = *in
	if in.PodMetric != nil {
		in, out := &in.PodMetric, &out.PodMetric
		*out = new(AIMServicePodMetricSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceMetricsSpec.
func (in *AIMServiceMetricsSpec) DeepCopy() *AIMServiceMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(AIMServiceMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceModel) DeepCopyInto(out *AIMServiceModel) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(AIMServiceModelCustom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceModel.
func (in *AIMServiceModel) DeepCopy() *AIMServiceModel {
	if in == nil {
		return nil
	}
	out := new(AIMServiceModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceModelCustom) DeepCopyInto(out *AIMServiceModelCustom) {
	*out = *in
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Hardware.DeepCopyInto(&out.Hardware)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceModelCustom.
func (in *AIMServiceModelCustom) DeepCopy() *AIMServiceModelCustom {
	if in == nil {
		return nil
	}
	out := new(AIMServiceModelCustom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceOverrides) DeepCopyInto(out *AIMServiceOverrides) {
	*out = *in
	in.AIMRuntimeParameters.DeepCopyInto(&out.AIMRuntimeParameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceOverrides.
func (in *AIMServiceOverrides) DeepCopy() *AIMServiceOverrides {
	if in == nil {
		return nil
	}
	out := new(AIMServiceOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServicePodMetric) DeepCopyInto(out *AIMServicePodMetric) {
	*out = *in
	if in.MetricNames != nil {
		in, out := &in.MetricNames, &out.MetricNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServicePodMetric.
func (in *AIMServicePodMetric) DeepCopy() *AIMServicePodMetric {
	if in == nil {
		return nil
	}
	out := new(AIMServicePodMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServicePodMetricSource) DeepCopyInto(out *AIMServicePodMetricSource) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(AIMServicePodMetric)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(AIMServiceMetricTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServicePodMetricSource.
func (in *AIMServicePodMetricSource) DeepCopy() *AIMServicePodMetricSource {
	if in == nil {
		return nil
	}
	out := new(AIMServicePodMetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceProfileConfig) DeepCopyInto(out *AIMServiceProfileConfig) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ProfileSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceProfileConfig.
func (in *AIMServiceProfileConfig) DeepCopy() *AIMServiceProfileConfig {
	if in == nil {
		return nil
	}
	out := new(AIMServiceProfileConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceProfileOverrides) DeepCopyInto(out *AIMServiceProfileOverrides) {
	*out = *in
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int32)
		**out = **in
	}
	if in.ContainerEnv != nil {
		in, out := &in.ContainerEnv, &out.ContainerEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EngineEnv != nil {
		in, out := &in.EngineEnv, &out.EngineEnv
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EngineArgs != nil {
		in, out := &in.EngineArgs, &out.EngineArgs
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceProfileOverrides.
func (in *AIMServiceProfileOverrides) DeepCopy() *AIMServiceProfileOverrides {
	if in == nil {
		return nil
	}
	out := new(AIMServiceProfileOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceRoutingStatus) DeepCopyInto(out *AIMServiceRoutingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceRoutingStatus.
func (in *AIMServiceRoutingStatus) DeepCopy() *AIMServiceRoutingStatus {
	if in == nil {
		return nil
	}
	out := new(AIMServiceRoutingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceRuntimeConfig) DeepCopyInto(out *AIMServiceRuntimeConfig) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(AIMStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(AIMRuntimeRoutingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleFromZero != nil {
		in, out := &in.ScaleFromZero, &out.ScaleFromZero
		*out = new(AIMScaleFromZeroConfig)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceRuntimeConfig.
func (in *AIMServiceRuntimeConfig) DeepCopy() *AIMServiceRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(AIMServiceRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceRuntimeStatus) DeepCopyInto(out *AIMServiceRuntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceRuntimeStatus.
func (in *AIMServiceRuntimeStatus) DeepCopy() *AIMServiceRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(AIMServiceRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceSpec) DeepCopyInto(out *AIMServiceSpec) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(AIMServiceModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(AIMServiceTemplateConfig)
		**out = **in
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(AIMServiceProfileConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProfileOverrides != nil {
		in, out := &in.ProfileOverrides, &out.ProfileOverrides
		*out = new(AIMServiceProfileOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make([]AIMServiceAdapterReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Caching != nil {
		in, out := &in.Caching, &out.Caching
		*out = new(AIMServiceCachingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CacheModel != nil {
		in, out := &in.CacheModel, &out.CacheModel
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.AutoScaling != nil {
		in, out := &in.AutoScaling, &out.AutoScaling
		*out = new(AIMServiceAutoScaling)
		(*in).DeepCopyInto(*out)
	}
	out.RuntimeConfigRef = in.RuntimeConfigRef
	in.AIMServiceRuntimeConfig.DeepCopyInto(&out.AIMServiceRuntimeConfig)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(AIMServiceOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceSpec.
func (in *AIMServiceSpec) DeepCopy() *AIMServiceSpec {
	if in == nil {
		return nil
	}
	out := new(AIMServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceStatus) DeepCopyInto(out *AIMServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedRuntimeConfig != nil {
		in, out := &in.ResolvedRuntimeConfig, &out.ResolvedRuntimeConfig
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ResolvedModel != nil {
		in, out := &in.ResolvedModel, &out.ResolvedModel
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(AIMServiceRoutingStatus)
		**out = **in
	}
	if in.ResolvedTemplate != nil {
		in, out := &in.ResolvedTemplate, &out.ResolvedTemplate
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ResolvedProfile != nil {
		in, out := &in.ResolvedProfile, &out.ResolvedProfile
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(AIMServiceCacheStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(AIMServiceRuntimeStatus)
		**out = **in
	}
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make([]AIMServiceAdapterStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceStatus.
func (in *AIMServiceStatus) DeepCopy() *AIMServiceStatus {
	if in == nil {
		return nil
	}
	out := new(AIMServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceTemplate) DeepCopyInto(out *AIMServiceTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceTemplate.
func (in *AIMServiceTemplate) DeepCopy() *AIMServiceTemplate {
	if in == nil {
		return nil
	}
	out := new(AIMServiceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMServiceTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceTemplateConfig) DeepCopyInto(out *AIMServiceTemplateConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceTemplateConfig.
func (in *AIMServiceTemplateConfig) DeepCopy() *AIMServiceTemplateConfig {
	if in == nil {
		return nil
	}
	out := new(AIMServiceTemplateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceTemplateList) DeepCopyInto(out *AIMServiceTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMServiceTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceTemplateList.
func (in *AIMServiceTemplateList) DeepCopy() *AIMServiceTemplateList {
	if in == nil {
		return nil
	}
	out := new(AIMServiceTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMServiceTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceTemplateSpec) DeepCopyInto(out *AIMServiceTemplateSpec) {
	*out = *in
	in.AIMServiceTemplateSpecCommon.DeepCopyInto(&out.AIMServiceTemplateSpecCommon)
	if in.Caching != nil {
		in, out := &in.Caching, &out.Caching
		*out = new(AIMTemplateCachingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceTemplateSpec.
func (in *AIMServiceTemplateSpec) DeepCopy() *AIMServiceTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AIMServiceTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceTemplateSpecCommon) DeepCopyInto(out *AIMServiceTemplateSpecCommon) {
	*out = *in
	in.AIMRuntimeParameters.DeepCopyInto(&out.AIMRuntimeParameters)
	out.RuntimeConfigRef = in.RuntimeConfigRef
	if in.CustomProfile != nil {
		in, out := &in.CustomProfile, &out.CustomProfile
		*out = new(AIMCustomProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(AIMProfileType)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceTemplateSpecCommon.
func (in *AIMServiceTemplateSpecCommon) DeepCopy() *AIMServiceTemplateSpecCommon {
	if in == nil {
		return nil
	}
	out := new(AIMServiceTemplateSpecCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMServiceTemplateStatus) DeepCopyInto(out *AIMServiceTemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedRuntimeConfig != nil {
		in, out := &in.ResolvedRuntimeConfig, &out.ResolvedRuntimeConfig
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ResolvedModel != nil {
		in, out := &in.ResolvedModel, &out.ResolvedModel
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ResolvedCache != nil {
		in, out := &in.ResolvedCache, &out.ResolvedCache
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.ResolvedHardware != nil {
		in, out := &in.ResolvedHardware, &out.ResolvedHardware
		*out = new(AIMHardwareRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedNodeAffinity != nil {
		in, out := &in.ResolvedNodeAffinity, &out.ResolvedNodeAffinity
		*out = new(v1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Profile != nil {
		in, out := &in.Profile, &out.Profile
		*out = new(AIMDiscoveredProfile)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscoveryJob != nil {
		in, out := &in.DiscoveryJob, &out.DiscoveryJob
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(DiscoveryState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMServiceTemplateStatus.
func (in *AIMServiceTemplateStatus) DeepCopy() *AIMServiceTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(AIMServiceTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMStorageConfig) DeepCopyInto(out *AIMStorageConfig) {
	*out = *in
	if in.DefaultStorageClassName != nil {
		in, out := &in.DefaultStorageClassName, &out.DefaultStorageClassName
		*out = new(string)
		**out = **in
	}
	if in.PVCHeadroomPercent != nil {
		in, out := &in.PVCHeadroomPercent, &out.PVCHeadroomPercent
		*out = new(int32)
		**out = **in
	}
	if in.DownloadFilter != nil {
		in, out := &in.DownloadFilter, &out.DownloadFilter
		*out = new(AIMDownloadFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.AdapterDiskStorageClassName != nil {
		in, out := &in.AdapterDiskStorageClassName, &out.AdapterDiskStorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AdapterDiskSize != nil {
		in, out := &in.AdapterDiskSize, &out.AdapterDiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMStorageConfig.
func (in *AIMStorageConfig) DeepCopy() *AIMStorageConfig {
	if in == nil {
		return nil
	}
	out := new(AIMStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateCache) DeepCopyInto(out *AIMTemplateCache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateCache.
func (in *AIMTemplateCache) DeepCopy() *AIMTemplateCache {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMTemplateCache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateCacheList) DeepCopyInto(out *AIMTemplateCacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIMTemplateCache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateCacheList.
func (in *AIMTemplateCacheList) DeepCopy() *AIMTemplateCacheList {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateCacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIMTemplateCacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateCacheSpec) DeepCopyInto(out *AIMTemplateCacheSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.RuntimeConfigRef = in.RuntimeConfigRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateCacheSpec.
func (in *AIMTemplateCacheSpec) DeepCopy() *AIMTemplateCacheSpec {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateCacheStatus) DeepCopyInto(out *AIMTemplateCacheStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolvedRuntimeConfig != nil {
		in, out := &in.ResolvedRuntimeConfig, &out.ResolvedRuntimeConfig
		*out = new(AIMResolvedReference)
		**out = **in
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make(map[string]AIMResolvedArtifact, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateCacheStatus.
func (in *AIMTemplateCacheStatus) DeepCopy() *AIMTemplateCacheStatus {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateCachingConfig) DeepCopyInto(out *AIMTemplateCachingConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateCachingConfig.
func (in *AIMTemplateCachingConfig) DeepCopy() *AIMTemplateCachingConfig {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateCachingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateCandidateResult) DeepCopyInto(out *AIMTemplateCandidateResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateCandidateResult.
func (in *AIMTemplateCandidateResult) DeepCopy() *AIMTemplateCandidateResult {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateCandidateResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMTemplateProfile) DeepCopyInto(out *AIMTemplateProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMTemplateProfile.
func (in *AIMTemplateProfile) DeepCopy() *AIMTemplateProfile {
	if in == nil {
		return nil
	}
	out := new(AIMTemplateProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactCacheConfig) DeepCopyInto(out *ArtifactCacheConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactCacheConfig.
func (in *ArtifactCacheConfig) DeepCopy() *ArtifactCacheConfig {
	if in == nil {
		return nil
	}
	out := new(ArtifactCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredProfileCounts) DeepCopyInto(out *DiscoveredProfileCounts) {
	*out = *in
	if in.ByHardware != nil {
		in, out := &in.ByHardware, &out.ByHardware
		*out = make([]ProfileHardwareGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredProfileCounts.
func (in *DiscoveredProfileCounts) DeepCopy() *DiscoveredProfileCounts {
	if in == nil {
		return nil
	}
	out := new(DiscoveredProfileCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryCacheReference) DeepCopyInto(out *DiscoveryCacheReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryCacheReference.
func (in *DiscoveryCacheReference) DeepCopy() *DiscoveryCacheReference {
	if in == nil {
		return nil
	}
	out := new(DiscoveryCacheReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryState) DeepCopyInto(out *DiscoveryState) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastIdentityCheckTime != nil {
		in, out := &in.LastIdentityCheckTime, &out.LastIdentityCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryState.
func (in *DiscoveryState) DeepCopy() *DiscoveryState {
	if in == nil {
		return nil
	}
	out := new(DiscoveryState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadProgress) DeepCopyInto(out *DownloadProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadProgress.
func (in *DownloadProgress) DeepCopy() *DownloadProgress {
	if in == nil {
		return nil
	}
	out := new(DownloadProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadState) DeepCopyInto(out *DownloadState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadState.
func (in *DownloadState) DeepCopy() *DownloadState {
	if in == nil {
		return nil
	}
	out := new(DownloadState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMetadata) DeepCopyInto(out *ImageMetadata) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ModelMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCIMetadata)
		**out = **in
	}
	if in.OriginalLabels != nil {
		in, out := &in.OriginalLabels, &out.OriginalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMetadata.
func (in *ImageMetadata) DeepCopy() *ImageMetadata {
	if in == nil {
		return nil
	}
	out := new(ImageMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedProfileCounts) DeepCopyInto(out *ManagedProfileCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedProfileCounts.
func (in *ManagedProfileCounts) DeepCopy() *ManagedProfileCounts {
	if in == nil {
		return nil
	}
	out := new(ManagedProfileCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelDiscoveryState) DeepCopyInto(out *ModelDiscoveryState) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelDiscoveryState.
func (in *ModelDiscoveryState) DeepCopy() *ModelDiscoveryState {
	if in == nil {
		return nil
	}
	out := new(ModelDiscoveryState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMetadata) DeepCopyInto(out *ModelMetadata) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Variants != nil {
		in, out := &in.Variants, &out.Variants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecommendedDeployments != nil {
		in, out := &in.RecommendedDeployments, &out.RecommendedDeployments
		*out = make([]RecommendedDeployment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMetadata.
func (in *ModelMetadata) DeepCopy() *ModelMetadata {
	if in == nil {
		return nil
	}
	out := new(ModelMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSourceFilter) DeepCopyInto(out *ModelSourceFilter) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSourceFilter.
func (in *ModelSourceFilter) DeepCopy() *ModelSourceFilter {
	if in == nil {
		return nil
	}
	out := new(ModelSourceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIMetadata) DeepCopyInto(out *OCIMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIMetadata.
func (in *OCIMetadata) DeepCopy() *OCIMetadata {
	if in == nil {
		return nil
	}
	out := new(OCIMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileHardwareGroup) DeepCopyInto(out *ProfileHardwareGroup) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]ProfileHardwareGroupEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileHardwareGroup.
func (in *ProfileHardwareGroup) DeepCopy() *ProfileHardwareGroup {
	if in == nil {
		return nil
	}
	out := new(ProfileHardwareGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileHardwareGroupEntry) DeepCopyInto(out *ProfileHardwareGroupEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileHardwareGroupEntry.
func (in *ProfileHardwareGroupEntry) DeepCopy() *ProfileHardwareGroupEntry {
	if in == nil {
		return nil
	}
	out := new(ProfileHardwareGroupEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileOverrides) DeepCopyInto(out *ProfileOverrides) {
	*out = *in
	if in.ModelSources != nil {
		in, out := &in.ModelSources, &out.ModelSources
		*out = make([]AIMModelSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int32)
		**out = **in
	}
	if in.ContainerEnv != nil {
		in, out := &in.ContainerEnv, &out.ContainerEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EngineEnv != nil {
		in, out := &in.EngineEnv, &out.EngineEnv
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EngineArgs != nil {
		in, out := &in.EngineArgs, &out.EngineArgs
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileOverrides.
func (in *ProfileOverrides) DeepCopy() *ProfileOverrides {
	if in == nil {
		return nil
	}
	out := new(ProfileOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSelector) DeepCopyInto(out *ProfileSelector) {
	*out = *in
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int32)
		**out = **in
	}
	if in.EngineArgs != nil {
		in, out := &in.EngineArgs, &out.EngineArgs
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelRef != nil {
		in, out := &in.ModelRef, &out.ModelRef
		*out = new(ProfileSelectorModelRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSelector.
func (in *ProfileSelector) DeepCopy() *ProfileSelector {
	if in == nil {
		return nil
	}
	out := new(ProfileSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSelectorModelRef) DeepCopyInto(out *ProfileSelectorModelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSelectorModelRef.
func (in *ProfileSelectorModelRef) DeepCopy() *ProfileSelectorModelRef {
	if in == nil {
		return nil
	}
	out := new(ProfileSelectorModelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSetReference) DeepCopyInto(out *ProfileSetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSetReference.
func (in *ProfileSetReference) DeepCopy() *ProfileSetReference {
	if in == nil {
		return nil
	}
	out := new(ProfileSetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSourceRef) DeepCopyInto(out *ProfileSourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSourceRef.
func (in *ProfileSourceRef) DeepCopy() *ProfileSourceRef {
	if in == nil {
		return nil
	}
	out := new(ProfileSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendedDeployment) DeepCopyInto(out *RecommendedDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendedDeployment.
func (in *RecommendedDeployment) DeepCopy() *RecommendedDeployment {
	if in == nil {
		return nil
	}
	out := new(RecommendedDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeConfigRef) DeepCopyInto(out *RuntimeConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeConfigRef.
func (in *RuntimeConfigRef) DeepCopy() *RuntimeConfigRef {
	if in == nil {
		return nil
	}
	out := new(RuntimeConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3AuthConfig) DeepCopyInto(out *S3AuthConfig) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(S3CredentialsSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3AuthConfig.
func (in *S3AuthConfig) DeepCopy() *S3AuthConfig {
	if in == nil {
		return nil
	}
	out := new(S3AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CABundleReference) DeepCopyInto(out *S3CABundleReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CABundleReference.
func (in *S3CABundleReference) DeepCopy() *S3CABundleReference {
	if in == nil {
		return nil
	}
	out := new(S3CABundleReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ConnectionConfig) DeepCopyInto(out *S3ConnectionConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(S3AuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(S3TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ConnectionConfig.
func (in *S3ConnectionConfig) DeepCopy() *S3ConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(S3ConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CredentialsSecretReference) DeepCopyInto(out *S3CredentialsSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CredentialsSecretReference.
func (in *S3CredentialsSecretReference) DeepCopy() *S3CredentialsSecretReference {
	if in == nil {
		return nil
	}
	out := new(S3CredentialsSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3TLSConfig) DeepCopyInto(out *S3TLSConfig) {
	*out = *in
	if in.CABundleRef != nil {
		in, out := &in.CABundleRef, &out.CABundleRef
		*out = new(S3CABundleReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3TLSConfig.
func (in *S3TLSConfig) DeepCopy() *S3TLSConfig {
	if in == nil {
		return nil
	}
	out := new(S3TLSConfig)
	in.DeepCopyInto(out)
	return out
}
