/*
MIT License

Copyright (c) 2025 Advanced Micro Devices, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package aimclustermodelsource

import (
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	aimv1alpha1 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha1"
	aimv1alpha2 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha2"
	"github.com/amd-enterprise-ai/aim-engine/internal/constants"
	"github.com/amd-enterprise-ai/aim-engine/internal/utils"
)

const (
	// LabelKeyModelSource is the label key used to identify the model source that created a cluster model.
	LabelKeyModelSource = constants.AimLabelDomain + "/model-source"

	annotationSourceRegistry   = constants.AimLabelDomain + "/source-registry"
	annotationSourceRepository = constants.AimLabelDomain + "/source-repository"
	annotationSourceTag        = constants.AimLabelDomain + "/source-tag"
	annotationSourceModelID    = constants.AimLabelDomain + "/source-model-id"
)

// buildClusterModel creates an AIMClusterModel from a source and discovered image.
//
// Registry discovery writes through v1alpha1, unchanged. Only modelId
// declarations need the v1alpha2 client (see buildDeclaredClusterModel), so
// image discovery is left on the version it has always used.
func buildClusterModel(
	source *aimv1alpha1.AIMClusterModelSource,
	img RegistryImage,
) *aimv1alpha1.AIMClusterModel {
	return &aimv1alpha1.AIMClusterModel{
		ObjectMeta: metav1.ObjectMeta{
			Name: generateModelName(img),
			Labels: map[string]string{
				LabelKeyModelSource:      source.Name,
				constants.LabelKeyOrigin: constants.LabelValueOriginAutoGenerated,
			},
			Annotations: map[string]string{
				annotationSourceRegistry:   img.Registry,
				annotationSourceRepository: img.Repository,
				annotationSourceTag:        img.Tag,
			},
		},
		Spec: aimv1alpha1.AIMModelSpec{
			Image:            img.ToImageURI(),
			ImagePullSecrets: source.Spec.ImagePullSecrets,
		},
	}
}

// buildDeclaredClusterModel materializes a spec.models entry.
//
// This one must be written as v1alpha2: the v1alpha1 AIMClusterModel CEL rejects
// spec.modelId outright ("spec.modelId is only supported on v1alpha2"). Reads
// are unaffected either way — v1alpha2 is the storage version and CEL runs on
// write — so the rest of this controller stays on v1alpha1.
func buildDeclaredClusterModel(
	source *aimv1alpha1.AIMClusterModelSource,
	declaration aimv1alpha1.AIMClusterModelSourceModel,
) (*aimv1alpha2.AIMClusterModel, error) {
	name, err := generateDeclaredModelName(declaration.ModelID)
	if err != nil {
		return nil, err
	}
	return &aimv1alpha2.AIMClusterModel{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
			Labels: map[string]string{
				LabelKeyModelSource:      source.Name,
				constants.LabelKeyOrigin: constants.LabelValueOriginAutoGenerated,
			},
			Annotations: map[string]string{
				annotationSourceModelID: declaration.ModelID,
			},
		},
		Spec: aimv1alpha1.AIMModelSpec{
			ModelID:     declaration.ModelID,
			AimId:       declaration.AimID,
			Source:      declaration.Source,
			Accelerator: declaration.Accelerator,
		},
	}, nil
}

func generateDeclaredModelName(modelID string) (string, error) {
	name, err := utils.GenerateDerivedName(
		[]string{modelID},
		utils.WithHashSource(modelID),
		utils.WithHashLength(6),
	)
	if err != nil {
		return "", fmt.Errorf("generate model name for declaration %q: %w", modelID, err)
	}
	return name, nil
}

func isModelOwnedBySource(model *aimv1alpha1.AIMClusterModel, sourceName string) bool {
	if model == nil {
		return false
	}
	return model.Labels[LabelKeyModelSource] == sourceName &&
		model.Labels[constants.LabelKeyOrigin] == constants.LabelValueOriginAutoGenerated
}

// generateModelName creates a Kubernetes-valid name from a registry image.
// It uses the repository and tag as name parts, with registry, repository, and tag
// as hash inputs for deterministic uniqueness.
//
// Format: <repository>-<tag>-<hash>
//
// Examples:
//
//	{Registry: "ghcr.io", Repository: "silogen/llama-3-8b", Tag: "v1.2.0"} -> silogen-llama-3-8b-v1-2-0-a1b2c3
//	{Registry: "docker.io", Repository: "library/nginx", Tag: "latest"} -> library-nginx-latest-e5f6g7
func generateModelName(img RegistryImage) string {
	// Use GenerateDerivedName with repository and tag as name parts
	// and registry, repository, tag as hash inputs for uniqueness
	name, _ := utils.GenerateDerivedName(
		[]string{img.Repository, img.Tag},
		utils.WithHashSource(img.Registry, img.Repository, img.Tag), // Hash inputs for determinism
		utils.WithHashLength(6),                                     // 6-char hash for collision avoidance
	)
	return name
}
